[package]
name = "ds_challenge"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = {version = "1", features = ["derive"]}
serde_json = "1"
serde_with = "3"
serde_any = "0"
anyhow = "1.0"
ulid = "1"
rand = "0"
once_map = "0"
